services:
  db:
    image: mysql:5.7.44
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && npm install --silent && bundle install --quiet && ./bin/dev"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3100"
      - "3036:3036"
    env_file: []
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: midlife_development
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db

volumes:
  db_data:
  bundle:
